// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmey3SGg1JtmZY9DFmDUjkTjvlpOpz5VU',
    appId: '1:1017308028178:web:65244bef4e7c0cac3aa7cb',
    messagingSenderId: '1017308028178',
    projectId: 'fir-gallery-2da4d',
    authDomain: 'fir-gallery-2da4d.firebaseapp.com',
    storageBucket: 'fir-gallery-2da4d.appspot.com',
    measurementId: 'G-SKXCG7EGWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABaj5-GRjdUdevWpWPOq2rrwmmw_HU6iU',
    appId: '1:1017308028178:android:c417a13fac1afa043aa7cb',
    messagingSenderId: '1017308028178',
    projectId: 'fir-gallery-2da4d',
    storageBucket: 'fir-gallery-2da4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz5EX1cca00yH_DKYr2BV2ZyWp7CU-vQM',
    appId: '1:1017308028178:ios:0ee900103cc8b3c73aa7cb',
    messagingSenderId: '1017308028178',
    projectId: 'fir-gallery-2da4d',
    storageBucket: 'fir-gallery-2da4d.appspot.com',
    iosClientId: '1017308028178-9rccpks5f92svci8oq0og58ld6pjmr59.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.gallery',
  );
}
